-- FOOD ITEMS

consumableItems = {
	{ -- 1
		name = "Apple",
		multipleCase = "Apples",
		hunger = 5.0,
		thirst = 2.0,
		health = 5,
		spawnChance = 50,
		randomFinds = {2,8},
		desc = "An apple a day keeps the zombie doctor away!",
		consumable = true,
		price = 3,
		stockAmount = {40,100},
	},
	{-- 2
		name = "Cola Bottle",
		multipleCase = "Cola Bottles",
		hunger = 2.0,
		thirst = 10.0,
		health = 1,
		spawnChance = 50,
		randomFinds = {2,4},
		desc = "Famous Cocaine-Containing Drink",
		consumable = true,
		price = 4,
		stockAmount = {40,100},
	},
	{-- 3
		name = "Milk Bottle",
		multipleCase = "Milk Bottles",
		hunger = 3.0,
		thirst = 12.0,
		health = 4,
		spawnChance = 35,
		randomFinds = {2,3},
		desc = "Galactic Taste.",
		consumable = true,
		price = 6,
		stockAmount = {30,70},
	},
	{-- 4
		name = "Chips Package",
		multipleCase = "Chips Packages",
		hunger = 10.0,
		thirst = -15.0,
		health = 1,
		spawnChance = 50,
		randomFinds = {2,3},
		desc = "Ah, this reminds me of my high school days.",
		consumable = true,
		price = 3,
		stockAmount = {40,100},
	},
	{-- 5
		name = "Beef",
		multipleCase = "Beeves",
		hunger = 20.0,
		thirst = -15.0,
		health = 5,
		spawnChance = 25,
		randomFinds = {2,5},
		desc = "Beef Jerk-who now?",
		consumable = true,
		price = 4,
		stockAmount = {40,100},
	},
	{-- 6
		name = "Beefium",
		multipleCase = "Beefiums",
		hunger = 30.0,
		thirst = -8.0,
		health = 6,
		spawnChance = 20,
		randomFinds = {2,2},
		desc = "Beefium, Beef Jerky enriched with vitamins and protein!",
		consumable = true,
		price = 10,
		stockAmount = {20,60},
	},
	{-- 7
		name = "Bandage",
		multipleCase = "Bandages",
		hunger = 0.0,
		thirst = 0.0,
		health = 20,
		spawnChance = 6,
		randomFinds = {2,3},
		desc = "Please do not apply on broken hearts.",
		consumable = true,
		price = 550,
		sellloss = 0.35,
		stockAmount = {0,30},
	},
	{-- 8
		name = "Orange Juice Pack",
		multipleCase = "Orange Juice Packs",
		hunger = 3.0,
		thirst = 8.0,
		health = 5,
		spawnChance = 50,
		randomFinds = {2,3},
		desc = "Tasty AND Healthy!",
		consumable = true,
		price = 6,
		stockAmount = {40,100},
	},
	{-- 9
		name = "Pizza Slice",
		multipleCase = "Pizza Slices",
		hunger = 20.0,
		thirst = -15.0,
		health = 5,
		spawnChance = 50,
		randomFinds = {2,4},
		desc = "Not that healthy but so delicious.",
		consumable = true,
		price = 3,
		stockAmount = {40,100},
	},
	{-- 10
		name = "Fried Chicken",
		multipleCase = "Fried Chickens",
		hunger = 5.0,
		thirst = -1.0,
		health = 5,
		spawnChance = 50,
		randomFinds = {2,6},
		desc = "Deep Fried is best fried.",
		consumable = true,
		price = 3,
		stockAmount = {40,100},
	},
	{-- 11
		name = "Small Medkit",
		multipleCase = "Small Medkits",
		hunger = 0.0,
		thirst = 0.0,
		health = 35,
		spawnChance = 8,
		randomFinds = {2,3},
		desc = "Mandatory in every Motorised Vehicle by Law, also useful if you are about to die.",
		consumable = true,
		price = 850,
		sellloss = 0.35,
		stockAmount = {0,25},
		interactionDelay = 5000,
	},
	{-- 12
		name = "Water Bottle",
		multipleCase = "Water Bottles",
		hunger = 0.0,
		thirst = 20.0,
		health = 5,
		spawnChance = 50,
		randomFinds = {2,4},
		desc = "Fresh, clean water.",
		consumable = true,
		price = 15,
		sellloss = 0.35,
		stockAmount = {40,100},
	},
	{-- 13
		name = "Engine Repair Kit",
		multipleCase = "Engine Repair Kits",
		desc = "Usable to repair most types of combustion engines",
		property = "vehiclerepair",
		spawnChance = 5,
		randomFinds = {2,2},
		consumable = false,
		price = 6000,
		sellloss = 0.35,
		stockAmount = {0,10},
	},
	{-- 14
		name = "Tyre Repair Kit",
		multipleCase = "Tyre Repair Kits",
		desc = "Usable to repair various types of tires",
		property = "tyrerepair",
		spawnChance = 5,
		randomFinds = {2,2},
		consumable = false,
		price = 3000,
		sellloss = 0.35,
		stockAmount = {0,10},
	},
	{-- 15
		name = "Twinkie",
		multipleCase = "Twinkies",
		hunger = 3.0,
		thirst = 1.0,
		health = 3,
		spawnChance = 50,
		randomFinds = {2,3},
		desc = "I hate coconut, not the taste, the consistency.",
		consumable = true,
		price = 3,
		stockAmount = {20,70},
	},
	{-- 16
		name = "Antibiotics",
		multipleCase = "Antibiotics",
		desc = "This will save my Life! people said, it didn't, but now it's here to save yours! Can heal infections.",
		property = "cureinfection",
		hunger = 0.0,
		thirst = 0.0,
		health = 0,
		spawnChance = 8,
		randomFinds = {2,3},
		consumable = true,
		price = 4000,
		sellloss = 0.35,
		stockAmount = {0,35},
		interactionDelay = 5000,
	},
	{-- 17
		name = "Money",
		multipleCase = "Money Bills",
		desc = "All i wanna do is...",
		property = "flipcoin",
		hunger = 0.0,
		thirst = 0.0,
		health = 0,
		spawnChance = 50,
		randomFinds = {2,100},
		consumable = false,
		infinite = true,
		stockAmount = 0,
	},
	{-- 18
		name = "Safe",
		multipleCase = "Safes",
		desc = "Keep your stuff safe from looters, Safe'n'Secure Safes will keep your Safe.. Safe.",
		property = "placeSafe",
		spawnChance = 2,
		randomFinds = {1,1},
		consumable = false,
		price = 42000,
		sellloss = 0.35,
		stockAmount = {0,5},
	},
	{-- 19
		name = "Gummy Bears Package",
		multipleCase = "Gummy Bears Packages",
		desc = "These laxatives aren't good for you, but so delicious.",
		hunger = 12.0,
		thirst = 0.0,
		health = -2,
		spawnChance = 50,
		randomFinds = {2,3},
		consumable = true,
		price = 2,
		stockAmount = {20,70},
	},
	{-- 20
		name = "Rotten Apple",
		multipleCase = "Rotten Apples",
		desc = "Only eat if you are absolutely sure, this will probably make you sick.",
		hunger = 5.0,
		thirst = -5.0,
		health = -10,
		spawnChance = 15,
		randomFinds = {1,2},
		consumable = true,
		stockAmount = 0,
	},
	{-- 21
		name = "Rotten Tomato",
		multipleCase = "Rotten Tomatoes",
		desc = "I feel like watching a movie right now.",
		hunger = 6.0,
		thirst = 8.0,
		health = -15,
		spawnChance = 15,
		randomFinds = {1,2},
		consumable = true,
		stockAmount = 0,
	},
	{-- 22
		name = "Can of Cat Food",
		multipleCase = "Cans of Cat Food",
		desc = "It's.. food, not particulary tasty but it sure is eatable.",
		hunger = 6.0,
		thirst = 3.0,
		health = 3,
		spawnChance = 30,
		randomFinds = {1,3},
		consumable = true,
		price = 3,
		sellloss = 0.40,
		stockAmount = 0,
	},
	{-- 23
		name = "Suicide Pill",
		multipleCase = "Suicide Pills",
		desc = "This'll finish the job.",
		hunger = 0.0,
		thirst = 0.0,
		health = -200,
		spawnChance = 5,
		randomFinds = {1,3},
		consumable = true,
		price = 3,
		sellloss = 0.10,
		stockAmount = 5,
	},
	{-- 24
		name = "MRE Kit",
		multipleCase = "MRE Kits",
		desc = "Everything you need to survive, for a while.",
		hunger = 25.0,
		thirst = 25.0,
		health = 15,
		spawnChance = 10,
		randomFinds = {1,3},
		consumable = true,
		price = 80,
		sellloss = 0.40,
		stockAmount = {1,6},
		interactionDelay = 5000,
	},
	{-- 25
		name = "Loot Crate",
		multipleCase = "Loot Crates",
		desc = "Loot Crates store loot, obviously, but wait, where's the key?",
		spawnChance = 1,
		randomFinds = {1,1},
		property = "useCrate",
		consumable = false,
		price = 10,
		stockAmount = 0,
	},
	{-- 26
		name = "Loot Crate Key",
		multipleCase = "Loot Crates Keys",
		desc = "Hey, it's a Key!",
		spawnChance = 0,
		randomFinds = {1,1},
		property = "useKey",
		consumable = false,
		price = false,
		stockAmount = 500,
	},
































	{ --27
		name = "Nightstick",
		hash = "weapon_Nightstick",
		model = "W_ME_Nightstick",
		hasammo = false,
		price = 5,
		sellloss = 0.35,
		spawnChance = 30,
		stockAmount = {10,50},
		isWeapon = true,
	},
	{--28
		name = "Hammer",
		hash = "weapon_Hammer",
		model = "W_ME_Hammer",
		hasammo = false,
		price = 5,
		sellloss = 0.35,
		spawnChance = 30,
		stockAmount = {10,50},
		isWeapon = true,
	},
	{--29
		name = "Golf Club",
		hash = "weapon_GolfClub",
		model = "W_ME_GClub",
		hasammo = false,
		price = 5,
		spawnChance = 30,
		stockAmount = {10,50},
		isWeapon = true,
	},
	{--30
		name = "Crowbar",
		hash = "weapon_Crowbar",
		model = "w_me_crowbar",
		hasammo = false,
		price = 5,
		sellloss = 0.35,
		spawnChance = 30,
		stockAmount = {10,50},
		isWeapon = true,
	},
	{--31
		name = "Switchblade",
		hash = "weapon_SwitchBlade",
		model = "w_me_switchblade",
		hasammo = false,
		price = 5,
		
		spawnChance = 30,
		stockAmount = {10,50},
		isWeapon = true,
	},
	{--32
		name = "Pistol",
		hash = "weapon_Pistol",
		model = "W_PI_PISTOL",
		hasammo = true,
		price = 280,
		sellloss = 0.20,
		spawnChance = 50,
		stockAmount = {0,20},
		isWeapon = true,
	},
	{--33
		name = "Combat Pistol",
		hash = "weapon_CombatPistol",
		model = "W_PI_COMBATPISTOL",
		hasammo = true,
		price = 300,
		sellloss = 0.20,
		spawnChance = 50,
		stockAmount = {0,20},
		isWeapon = true,
	},
	{--34
		name = "AP Pistol",
		hash = "weapon_APPistol",
		model = "W_PI_APPISTOL",
		hasammo = true,
		price = 950,
		sellloss = 0.20,
		spawnChance = 30,
		stockAmount = {0,20},
		isWeapon = true,
	},
	{--35
		name = "Pistol 50.",
		hash = "weapon_Pistol50",
		model = "W_PI_PISTOL50",
		hasammo = true,
		price = 650,
		sellloss = 0.20,
		spawnChance = 45,
		stockAmount = {0,18},
		isWeapon = true,
	},
	{--36
		name = "Flare Gun",
		hash = "weapon_FlareGun",
		model = "w_pi_flaregun",
		hasammo = true,
		price = false,
		spawnChance = 0,
		stockAmount = 0,
		isWeapon = true,
	},
	{--37
		name = "Marksman Pistol",
		hash = "weapon_MarksmanPistol",
		model = "W_PI_SingleShot",
		hasammo = true,
		price = 1000,
		sellloss = 0.10,
		spawnChance = 40,
		stockAmount = {0,10},
		isWeapon = true,
	},
	{--38
		name = "Revolver",
		hash = "weapon_Revolver",
		model = "w_pi_revolver",
		hasammo = true,
		price = 360,
		sellloss = 0.10,
		spawnChance = 45,
		stockAmount = {0,18},
		isWeapon = true,
	},
	{--39
		name = "Micro SMG",
		hash = "weapon_MicroSMG",
		model = "W_SB_MICROSMG",
		hasammo = true,
		price = 1300,
		sellloss = 0.20,
		spawnChance = 20,
		stockAmount = {0,17},
		isWeapon = true,
	},
	{--40
		name = "SMG",
		hash = "weapon_SMG",
		model = "W_SB_SMG",
		hasammo = true,
		price = 1650,
		sellloss = 0.20,
		spawnChance = 20,
		stockAmount = {0,14},
		isWeapon = true,
	},
	{--41
		name = "Assault SMG",
		hash = "weapon_AssaultSMG",
		model = "W_SB_SMG",
		hasammo = true,
		price = 1450,
		sellloss = 0.20,
		spawnChance = 15,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--42
		name = "Combat PDW",
		hash = "weapon_CombatPDW",
		model = "W_SB_PDW",
		hasammo = true,
		price = 1850,
		sellloss = 0.20,
		spawnChance = 15,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--43
		name = "MG",
		hash = "weapon_MG",
		model = "W_MG_MG",
		hasammo = true,
		price = 6500,
		sellloss = 0.20,
		spawnChance = 18,
		stockAmount = {0,6},
		isWeapon = true,
	},
	{--44
		name = "Combat MG",
		hash = "weapon_CombatMG",
		model = "W_MG_COMBATMG",
		hasammo = true,
		price = 6500,
		sellloss = 0.20,
		spawnChance = 15,
		stockAmount = {0,4},
		isWeapon = true,
	},
	{--45
		name = "Pump Shotgun",
		hash = "weapon_PumpShotgun",
		model = "W_SG_PUMPSHOTGUN",
		hasammo = true,
		price = 2500,
		sellloss = 0.20,
		spawnChance = 25,
		stockAmount = {0,16},
		isWeapon = true,
	},
	{--46
		name = "Sawn Off Shotgun",
		hash = "weapon_SawnOffShotgun",
		model = "W_SG_SawnOff",
		hasammo = true,
		price = 600,
		sellloss = 0.1,
		spawnChance = 40,
		stockAmount = {0,15},
		isWeapon = true,
	},
	{--47
		name = "Assault Shotgun",
		hash = "weapon_AssaultShotgun",
		model = "W_SG_ASSAULTSHOTGUN",
		hasammo = true,
		price = 8500,
		sellloss = 0.20,
		spawnChance = 10,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--48
		name = "Bullpup Shotgun",
		hash = "weapon_BullpupShotgun",
		model = "w_sg_bullpupshotgun",
		hasammo = true,
		price = 5500,
		sellloss = 0.20,
		spawnChance = 25,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--49
		name = "Double Barrel Shotgun",
		hash = "weapon_dbshotgun",
		model = "w_sg_doublebarrel",
		hasammo = true,
		price = 1000,
		sellloss = 0.1,
		spawnChance = 35,
		stockAmount = {0,10},
		isWeapon = true,
	},
	{--50
		name = "Stungun",
		hash = "weapon_StunGun",
		model = "w_pi_stungun",
		hasammo = false,
		price = 100,
		sellloss = 0.35,
		spawnChance = 40,
		stockAmount = {0,1},
		isWeapon = true,
	},
	{--51
		name = "Sniper Rifle",
		hash = "weapon_SniperRifle",
		model = "w_sr_sniperrifle",
		hasammo = true,
		price = 15000,
		sellloss = 0.20,
		spawnChance = 8,
		stockAmount = {0,8},
		isWeapon = true,
	},
	{--52
		name = "Heavy Sniper",
		hash = "weapon_HeavySniper",
		model = "w_sr_sniperrifle",
		hasammo = true,
		price = 25000,
		sellloss = 0.20,
		spawnChance = 4,
		stockAmount = {0,5},
		isWeapon = true,
	},
	{--53
		name = "Grenade",
		hash = "weapon_Grenade",
		model = "w_ex_grenadefrag",
		hasammo = true,
		price = 10000,
		sellloss = 0.1,
		spawnChance = 4,
		stockAmount = {0,5},
		isWeapon = true,
	},
	{--54
		name = "Sticky Bomb",
		hash = "weapon_StickyBomb",
		model = "w_ex_grenadefrag",
		hasammo = true,
		price = 30000,
		sellloss = 0.01,
		spawnChance = 0,
		stockAmount = 0,
		isWeapon = true,
	},
	{--55
		name = "Smoke Grenade",
		hash = "weapon_SmokeGrenade",
		model = "w_ex_grenadesmoke",
		hasammo = true,
		price = 200,
		sellloss = 0.20,
		spawnChance = 15,
		stockAmount = {0,10},
		isWeapon = true,
	},
	{--56
		name = "Molotov",
		hash = "weapon_Molotov",
		model = "w_ex_molotov",
		hasammo = true,
		price = 2000,
		sellloss = 0.20,
		spawnChance = 10,
		stockAmount = {0,25},
		isWeapon = true,
	},
	{--57
		name = "Petrol Can",
		hash = "weapon_PetrolCan",
		model = "prop_cs_petrol_can",
		desc = "Don't drink this.",
		property = "vehiclerefuel",
		spawnChance = 18,
		consumable = false,
		price = 1000,
		sellloss = 0.20,
		stockAmount = {0,10},
	},
	{--58
		name = "SNS Pistol",
		hash = "weapon_SNSPistol",
		model = "w_pi_sns_pistol",
		hasammo = true,
		price = 400,
		sellloss = 0.20,
		spawnChance = 40,
		stockAmount = {0,20},
		isWeapon = true,
	},
	{--59
		name = "Special Carbine",
		hash = "weapon_SpecialCarbine",
		model = "w_ar_specialcarbine",
		hasammo = true,
		price = 3800,
		sellloss = 0.20,
		spawnChance = 28,
		stockAmount = {1,15},
		isWeapon = true,
	},
	{--60
		name = "Heavy Pistol",
		hash = "weapon_HeavyPistol",
		model = "w_pi_heavypistol",
		hasammo = true,
		price = 700,
		sellloss = 0.1,
		spawnChance = 35,
		stockAmount = {2,20},
		isWeapon = true,
	},
	{--61
		name = "Bullpup Rifle",
		hash = "weapon_BullpupRifle",
		model = "w_ar_bullpuprifle",
		hasammo = true,
		price = 4500,
		sellloss = 0.20,
		spawnChance = 25,
		stockAmount = {1,10},
		isWeapon = true,
	},
	{--62
		name = "Vintage Pistol",
		hash = "weapon_VintagePistol",
		model = "w_pi_vintage_pistol",
		hasammo = true,
		price = 350,
		sellloss = 0.1,
		spawnChance = 40,
		stockAmount = {0,6},
		isWeapon = true,
	},
	{--63
		name = "Dagger",
		hash = "weapon_Dagger",
		model = "w_me_dagger",
		hasammo = false,
		price = 10,
		spawnChance = 35,
		sellloss = 0.1,
		stockAmount = {0,25},
		isWeapon = true,
	},
	{--64
		name = "Marksman Rifle",
		hash = "weapon_MarksmanRifle",
		model = "w_sr_marksmanrifle",
		hasammo = true,
		price = 23000,
		sellloss = 0.1,
		spawnChance = 6,
		stockAmount = {0,6},
		isWeapon = true,
	},
	{--65
		name = "Heavy Shotgun",
		hash = "weapon_HeavyShotgun",
		model = "w_sg_heavyshotgun",
		hasammo = true,
		price = 8000,
		sellloss = 0.1,
		spawnChance = 12,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--66
		name = "Gusenberg",
		hash = "weapon_Gusenberg",
		model = "w_sb_gusenberg",
		hasammo = true,
		price = 3600,
		sellloss = 0.10,
		spawnChance = 40,
		stockAmount = {0,20},
		isWeapon = true,
	},
	{--67
		name = "Machete",
		hash = "weapon_Machete",
		model = "w_me_machette_lr",
		hasammo = false,
		price = 15,
		spawnChance = 45,
		stockAmount = {5,30},
		isWeapon = true,
	},
	{--68
		name = "Machine Pistol",
		hash = "weapon_MachinePistol",
		model = "w_sb_compactsmg",
		hasammo = true,
		price = 3600,
		sellloss = 0.1,
		spawnChance = 45,
		stockAmount = {1,12},
		isWeapon = true,
	},
	{--69
		name = "Sweeper Shotgun",
		hash = "WEAPON_AUTOSHOTGUN",
		model = "w_sg_sweeper",
		hasammo = true,
		price = 8900,
		sellloss = 0.1,
		spawnChance = 25,
		stockAmount = {0,10},
		isWeapon = true,
	},
	{--70
		name = "Battle Axe",
		hash = "weapon_BattleAxe",
		model = "w_me_battleaxe",
		hasammo = false,
		price = 10,
		spawnChance = 45,
		stockAmount = {0,50},
		isWeapon = true,
	},
	{--71
		name = "Mini SMG",
		hash = "weapon_MiniSMG",
		model = "w_sb_minismg",
		hasammo = true,
		price = 2600,
		sellloss = 0.10,
		spawnChance = 40,
		stockAmount = {0,15},
		isWeapon = true,
	},
	{--72
		name = "Pipe Bomb",
		hash = "weapon_PipeBomb",
		model = "w_ex_pipebomb",
		hasammo = true,
		price = 16000,
		sellloss = 0.05,
		spawnChance = 1,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--73
		name = "Pool Cue",
		hash = "weapon_PoolCue",
		model = "w_me_poolcue",
		hasammo = false,
		price = 10,
		spawnChance = 40,
		stockAmount = {0,50},
		isWeapon = true,
	},
	{--74
		name = "Wrench",
		hash = "weapon_Wrench",
		model = "w_me_wrench",
		hasammo = false,
		price = 10,
		spawnChance = 35,
		stockAmount = {0,50},
		isWeapon = true,
	},
	{--75
		name = "Pistol MK2",
		hash = "weapon_Pistol_Mk2",
		model = "w_pi_sns_pistolmk2",
		hasammo = true,
		price = 860,
		sellloss = 0.10,
		spawnChance = 50,
		stockAmount = {0,20},
		isWeapon = true,
	},
	{--76
		name = "Assault Rifle MK2",
		hash = "weapon_AssaultRifle_Mk2",
		model = "w_ar_assaultriflemk2",
		hasammo = true,
		price = 6800,
		sellloss = 0.10,
		spawnChance = 25,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--77
		name = "Carbine Rifle MK2",
		hash = "weapon_CarbineRifle_Mk2",
		model = "w_ar_carbineriflemk2",
		hasammo = true,
		price = 6500,
		sellloss = 0.10,
		spawnChance = 25,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--78
		name = "Combat MG MK2",
		hash = "weapon_CombatMG_Mk2",
		model = "w_mg_combatmgmk2",
		hasammo = true,
		price = 10000,
		sellloss = 0.10,
		spawnChance = 10,
		stockAmount = {0,6},
		isWeapon = true,
	},
	{--79
		name = "Heavy Sniper MK2",
		hash = "weapon_HeavySniper_Mk2",
		model = "w_sr_heavysnipermk2",
		hasammo = true,
		price = 35000,
		sellloss = 0.10,
		spawnChance = 5,
		stockAmount = {0,2},
		isWeapon = true,
	},
	{--80
		name = "Compact Rifle",
		hash = "WEAPON_COMPACTRIFLE",
		model = "w_ar_assaultrifle_smg",
		hasammo = true,
		price = 3200,
		sellloss = 0.10,
		spawnChance = 30,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--81
		name = "Marksman Rifle MK2",
		hash = "WEAPON_MARKSMANRIFLE_MK2",
		model = "w_sr_marksmanriflemk2",
		hasammo = true,
		price = 28000,
		sellloss = 0.10,
		spawnChance = 8,
		stockAmount = {0,5},
		isWeapon = true,
	},
	{--82
		name = "Carbine Rifle",
		hash = "weapon_CarbineRifle",
		model = "w_ar_carbinerifle",
		hasammo = true,
		price = 5000,
		sellloss = 0.10,
		spawnChance = 25,
		stockAmount = {0,12},
		isWeapon = true,
	},
	{--83
		name = "Bullpup Rifle Mk2",
		hash = "weapon_BullpupRifle_MK2",
		model = "w_ar_bullpupriflemk2",
		hasammo = true,
		price = 5000,
		sellloss = 0.10,
		spawnChance = 25,
		stockAmount = {1,8},
		isWeapon = true,
	},
	{--84
		name = "Special Carbine Mk2",
		hash = "weapon_SpecialCarbine_MK2",
		model = "w_ar_specialcarbinemk2",
		hasammo = true,
		price = 5000,
		sellloss = 0.10,
		spawnChance = 28,
		stockAmount = {1,15},
		isWeapon = true,
	},
	{--85
		name = "Revolver Mk2",
		hash = "WEAPON_REVOLVER_MK2",
		model = "w_pi_revolver",
		hasammo = true,
		price = 750,
		sellloss = 0.10,
		spawnChance = 25,
		stockAmount = {0,18},
		isWeapon = true,
	},
	{--86
		name = "Pump Shotgun Mk2",
		hash = "weapon_PumpShotgun_MK2",
		model = "W_SG_PUMPSHOTGUN",
		hasammo = true,
		price = 3000,
		sellloss = 0.10,
		spawnChance = 35,
		stockAmount = {0,13},
		isWeapon = true,
	},
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	{-- 87
		name = "Airdrop Marker",
		multipleCase = "Airdrop Markers",
		desc = "Signals an Airdrop Plane to drop you a supply crate",
		spawnChance = 6,
		randomFinds = {1,1},
		property = "signalAirdrop",
		consumable = false,
		price = false,
		stockAmount = 0,
	},
	{-- 88
		name = "Binocular",
		multipleCase = "Binoculars",
		desc = "Beautiful View, isn't it?",
		spawnChance = 20,
		randomFinds = {1,1},
		property = "useBinos",
		consumable = false,
		price = 160,
		sellloss = 0.35,
		stockAmount = {0,10},
		infinite = true,
	},
	{-- 89
		name = "Infrared Goggle",
		multipleCase = "Infrared Goggles",
		desc = "If you see red, run.",
		spawnChance = 0,
		randomFinds = {1,1},
		property = "useIR",
		requiredbatteries = 4,
		consumable = false,
		price = 100000,
		sellloss = 0.05,
		stockAmount = {0,0},
		infinite = true,
	},
	{-- 90
		name = "Night Vision Goggle",
		multipleCase = "Night Vision Goggles",
		desc = "Have Superior Vision at night, just don't look into light.",
		spawnChance = 1,
		randomFinds = {1,1},
		property = "useNV",
		requiredbatteries = 4,
		consumable = false,
		price = 30000,
		sellloss = 0.1,
		stockAmount = {0,0},
		infinite = true,
	},
	{-- 91
		name = "Rechargeable Battery",
		multipleCase = "Rechargeable Batteries",
		desc = "Powers most Electronics these days.",
		spawnChance = 6,
		randomFinds = {1,4},
		property = "useAAAwithItem",
		consumable = false,
		price = 600,
		sellloss = 0.35,
		stockAmount = {0,10},
	},
	
	{-- 92
		name = "Amateur CB Radio",
		multipleCase = "Amateur CB Radios",
		desc = "CB Radio with decent range, only supports AM Radio",
		spawnChance = 0, -- 6
		randomFinds = {1,1},
		property = "useCBAmateur",
		consumable = false,
		price = 1200,
		sellloss = 0.0,
		stockAmount = {0,10},
		radioTex = "basicradio",
	},
	
	{-- 93
		name = "Enthusiast CB Radio",
		multipleCase = "Enthusiast CB Radios",
		desc = "CB Radio with good range, supports AM and FM",
		spawnChance = 3, -- 3
		randomFinds = {1,1},
		property = "useCBAmateur",
		consumable = false,
		price = 5000,
		sellloss = 0.45,
		stockAmount = {0,5},
	},
	
	{-- 94
		name = "Professional CB Radio",
		multipleCase = "Professional CB Radios",
		desc = "CB Radio with huge range, supports AM and FM",
		spawnChance = 1, -- 1
		randomFinds = {1,1},
		property = "useCBAmateur",
		consumable = false,
		price = 10000,
		sellloss = 0.45,
		stockAmount = {0,3},
	},
	
	{-- 95
		name = "Heat Pack",
		multipleCase = "Heat Packs",
		desc = "Increases Body Temperature over time",
		spawnChance = 0, 
		randomFinds = {1,2},
		property = "useHeatPack",
		consumable = false,
		price = 600,
		sellloss = 0.45,
		stockAmount = {0,0},
	},


}

consumableItems.count = {}
for i,Consumable in ipairs(consumableItems) do
	if not consumableItems[i].randomFinds then
		consumableItems[i].randomFinds = {1,1}
	end
	consumableItems.count[i] = 0.0
	if consumableItems[i].requiredbatteries then
		consumableItems[i].charge = 0
	end
end

-- deal with spawn chances
itemChances = {}
weaponChances = {}
for i,Consumable in ipairs(consumableItems) do
	if not Consumable.model then
		consumableItems[i].model = "Prop_Drug_package_02"
	end
	if not Consumable.isWeapon then
		for index = 1, Consumable.spawnChance do
			table.insert(itemChances, i)
		end
	else
		for index = 1, Consumable.spawnChance do
			table.insert(weaponChances, i)
		end
	end
end




-- A list of vehicles that should be spawned
spawnableCars = {
	{model="Adder",chance=1},
	{model="Akuma",chance=1},
	{model="Alpha",chance=20},
	{model="Ambulance",chance=20},
	{model="Annihilator",chance=2},
	{model="Ardent",chance=1},
	{model="Asea",chance=15},
	{model="Asea2",chance=5},
	{model="Asterope",chance=15},
	{model="Avarus",chance=10},
	{model="Bagger",chance=10},
	{model="Baller",chance=15},
	{model="Baller2",chance=8},
	{model="Baller3",chance=1},
	{model="Baller4",chance=1},
	{model="Baller5",chance=1},
	{model="Baller6",chance=1},
	{model="Banshee",chance=5},
	{model="Banshee2",chance=1},
	{model="Barracks",chance=12},
	{model="Barracks2",chance=12},
	{model="Barracks3",chance=12},
	{model="Bati",chance=8},
	{model="Bati2",chance=8},
	{model="Benson",chance=15},
	{model="Besra",chance=1},
	{model="BestiaGTS",chance=1},
	{model="BF400",chance=15},
	{model="BfInjection",chance=30},
	{model="Biff",chance=25},
	{model="Bifta",chance=30},
	{model="Bison",chance=25},
	{model="Bison2",chance=5},
	{model="Bison3",chance=5},
	{model="BJXL",chance=15},
	{model="Blade",chance=8},
	{model="Blazer",chance=17},
	{model="Blazer2",chance=17},
	{model="Blazer3",chance=1},
	{model="Blazer4",chance=1},
	{model="Blazer5",chance=1},
	{model="Blista",chance=25},
	{model="Blista2",chance=5},
	{model="Blista3",chance=5},
	{model="Bmx",chance=40},
	{model="BobcatXL",chance=15},
	{model="Bodhi2",chance=1},
	{model="Boxville",chance=20},
	{model="Boxville2",chance=20},
	{model="Boxville3",chance=20},
	{model="Boxville4",chance=20},
	{model="Brawler",chance=10},
	{model="Brickade",chance=18},
	{model="Brioso",chance=10},
	{model="BType",chance=7},
	{model="BType2",chance=7},
	{model="BType3",chance=7},
	{model="Buccaneer",chance=7},
	{model="Buccaneer2",chance=12},
	{model="Buffalo",chance=5},
	{model="Buffalo2",chance=1},
	{model="Buffalo3",chance=1},
	{model="Bulldozer",chance=20},
	{model="Bullet",chance=1},
	{model="Burrito",chance=30},
	{model="Burrito2",chance=30},
	{model="Burrito3",chance=30},
	{model="Burrito4",chance=30},
	{model="Burrito5",chance=30},
	{model="Bus",chance=20},
	{model="Buzzard",chance=3},
	{model="Buzzard2",chance=3},
	{model="Caddy",chance=10},
	{model="Caddy2",chance=10},
	{model="Caddy3",chance=10},
	{model="Camper",chance=25},
	{model="Carbonizzare",chance=1},
	{model="CarbonRS",chance=1},
	{model="Cargobob",chance=2},
	{model="Cargobob2",chance=2},
	{model="Cargobob3",chance=2},
	{model="Cargobob4",chance=2},
	{model="Casco",chance=1},
	{model="Cavalcade",chance=5},
	{model="Cavalcade2",chance=5},
	{model="Cheetah",chance=1},
	{model="Cheetah2",chance=1},
	{model="Chimera",chance=5},
	{model="Chino",chance=1},
	{model="Chino2",chance=5},
	{model="Cliffhanger",chance=20},
	{model="Coach",chance=25},
	{model="Cog55",chance=1},
	{model="Cog552",chance=1},
	{model="CogCabrio",chance=1},
	{model="Cognoscenti",chance=1},
	{model="Cognoscenti2",chance=1},
	{model="Comet2",chance=1},
	{model="Comet3",chance=1},
	{model="Comet4",chance=26},
	{model="Contender",chance=1},
	{model="Coquette",chance=1},
	{model="Coquette2",chance=1},
	{model="Coquette3",chance=1},
	{model="Cruiser",chance=6},
	{model="Cuban800",chance=7},
	{model="Cutter",chance=1},
	{model="Daemon",chance=8},
	{model="Daemon2",chance=8},
	{model="Defiler",chance=1},
	{model="Diablous",chance=1},
	{model="Diablous2",chance=1},
	{model="Dilettante",chance=1},
	{model="Dilettante2",chance=1},
	{model="Dinghy",chance=1},
	{model="Dinghy2",chance=1},
	{model="Dinghy3",chance=1},
	{model="Dinghy4",chance=1},
	{model="DLoader",chance=28},
	{model="Docktug",chance=5},
	{model="Dodo",chance=5},
	{model="Dominator",chance=1},
	{model="Dominator2",chance=1},
	{model="Double",chance=1},
	{model="Dubsta",chance=1},
	{model="Dubsta2",chance=10},
	{model="Dubsta3",chance=25},
	{model="Dukes",chance=6},
	{model="Dukes2",chance=25},
	{model="Dune",chance=45},
	{model="Dune2",chance=1},
	{model="Dune3",chance=12},
	{model="Dune4",chance=12},
	{model="Dune5",chance=10},
	{model="Duster",chance=1},
	{model="Elegy",chance=1},
	{model="Elegy2",chance=1},
	{model="Emperor",chance=15},
	{model="Emperor2",chance=35},
	{model="Emperor3",chance=1},
	{model="Enduro",chance=25},
	{model="EntityXF",chance=1},
	{model="Esskey",chance=1},
	{model="Exemplar",chance=1},
	{model="F620",chance=1},
	{model="Faction",chance=1},
	{model="Faction2",chance=1},
	{model="Faction3",chance=1},
	{model="Faggio",chance=20},
	{model="Faggio2",chance=1},
	{model="Faggio3",chance=5},
	{model="FBI",chance=1},
	{model="FBI2",chance=1},
	{model="FCR",chance=1},
	{model="FCR2",chance=1},
	{model="Felon",chance=1},
	{model="Felon2",chance=1},
	{model="Feltzer2",chance=1},
	{model="Feltzer3",chance=1},
	{model="FireTruk",chance=25},
	{model="Fixter",chance=15},
	{model="Flatbed",chance=1},
	{model="Forklift",chance=5},
	{model="FMJ",chance=1},
	{model="FQ2",chance=1},
	{model="Frogger",chance=10},
	{model="Frogger2",chance=10},
	{model="Fugitive",chance=1},
	{model="Furoregt",chance=1},
	{model="Fusilade",chance=1},
	{model="Futo",chance=20},
	{model="Gargoyle",chance=1},
	{model="Gauntlet",chance=1},
	{model="Gauntlet2",chance=1},
	{model="GBurrito",chance=6},
	{model="GBurrito2",chance=6},
	{model="Glendale",chance=1},
	{model="GP1",chance=1},
	{model="Granger",chance=15},
	{model="Gresley",chance=7},
	{model="Guardian",chance=18},
	{model="Habanero",chance=7},
	{model="Hakuchou",chance=7},
	{model="Hakuchou2",chance=1},
	{model="HalfTrack",chance=6},
	{model="Handler",chance=1},
	{model="Hauler",chance=16},
	{model="Hauler2",chance=25},
	{model="Hexer",chance=1},
	{model="Hotknife",chance=10},
	{model="Huntley",chance=12},
	{model="Hydra",chance=1},
	{model="Infernus",chance=5},
	{model="Infernus2",chance=5},
	{model="Ingot",chance=5},
	{model="Innovation",chance=5},
	{model="Insurgent2",chance=1},
	{model="Intruder",chance=7},
	{model="Issi2",chance=5},
	{model="ItaliGTB",chance=1},
	{model="ItaliGTB2",chance=1},
	{model="Jackal",chance=1},
	{model="JB700",chance=1},
	{model="Jester",chance=1},
	{model="Jester2",chance=1},
	{model="Jetmax",chance=1},
	{model="Journey",chance=25},
	{model="Kalahari",chance=4},
	{model="Khamelion",chance=1},
	{model="Kuruma",chance=4},
	{model="Kuruma2",chance=8},
	{model="Landstalker",chance=5},
	{model="LE7B",chance=1},
	{model="Lectro",chance=1},
	{model="Lguard",chance=10},
	{model="Limo2",chance=1},
	{model="Lurcher",chance=1},
	{model="Lynx",chance=1},
	{model="Mamba",chance=1},
	{model="Mammatus",chance=10},
	{model="Manana",chance=5},
	{model="Manchez",chance=25},
	{model="Marquis",chance=1},
	{model="Marshall",chance=1},
	{model="Massacro",chance=1},
	{model="Massacro2",chance=1},
	{model="Maverick",chance=1},
	{model="Mesa",chance=1},
	{model="Mesa2",chance=1},
	{model="Mesa3",chance=25},
	{model="Minivan",chance=1},
	{model="Minivan2",chance=1},
	{model="Mixer",chance=20},
	{model="Mixer2",chance=20},
	{model="Monroe",chance=5},
	{model="Monster",chance=1},
	{model="Moonbeam",chance=1},
	{model="Moonbeam2",chance=1},
	{model="Mower",chance=1},
	{model="Mule",chance=15},
	{model="Mule2",chance=15},
	{model="Mule3",chance=15},
	{model="Nemesis",chance=1},
	{model="Nero",chance=1},
	{model="Nero2",chance=1},
	{model="Nightblade",chance=1},
	{model="Nightshade",chance=1},
	{model="Nimbus",chance=1},
	{model="Ninef",chance=1},
	{model="Ninef2",chance=1},
	{model="Omnis",chance=1},
	{model="Oracle",chance=35},
	{model="Oracle2",chance=25},
	{model="Osiris",chance=1},
	{model="Packer",chance=13},
	{model="Panto",chance=30},
	{model="Paradise",chance=1},
	{model="Patriot",chance=20},
	{model="PBus",chance=18},
	{model="PCJ",chance=1},
	{model="Penetrator",chance=1},
	{model="Penumbra",chance=25},
	{model="Peyote",chance=25},
	{model="Pfister811",chance=1},
	{model="Phantom",chance=10},
	{model="Phantom3",chance=10},
	{model="Phoenix",chance=20},
	{model="Picador",chance=20},
	{model="Pigalle",chance=20},
	{model="Police",chance=30},
	{model="Police2",chance=30},
	{model="Police3",chance=30},
	{model="Police4",chance=30},
	{model="Policeb",chance=30},
	{model="PoliceOld1",chance=1},
	{model="PoliceOld2",chance=1},
	{model="PoliceT",chance=15},
	{model="Polmav",chance=1},
	{model="Pony",chance=25},
	{model="Pony2",chance=25},
	{model="Pounder",chance=12},
	{model="Prairie",chance=20},
	{model="Pranger",chance=10},
	{model="Predator",chance=1},
	{model="Premier",chance=25},
	{model="Primo",chance=20},
	{model="Primo2",chance=20},
	{model="Prototipo",chance=1},
	{model="Radi",chance=20},
	{model="RancherXL",chance=30},
	{model="RancherXL2",chance=1},
	{model="RallyTruck",chance=19},
	{model="RapidGT",chance=1},
	{model="RapidGT2",chance=1},
	{model="Raptor",chance=1},
	{model="RatBike",chance=24},
	{model="RatLoader",chance=26},
	{model="RatLoader2",chance=26},
	{model="Reaper",chance=1},
	{model="Rebel",chance=25},
	{model="Rebel2",chance=6},
	{model="Regina",chance=35},
	{model="RentalBus",chance=1},
	{model="Rhapsody",chance=10},
	{model="Riot",chance=15},
	{model="Rocoto",chance=20},
	{model="Romero",chance=10},
	{model="Rubble",chance=15},
	{model="Ruffian",chance=1},
	{model="Ruiner",chance=15},
	{model="Rumpo",chance=35},
	{model="Rumpo2",chance=5},
	{model="Rumpo3",chance=18},
	{model="Ruston",chance=1},
	{model="SabreGT",chance=15},
	{model="SabreGT2",chance=1},
	{model="Sadler",chance=5},
	{model="Sadler2",chance=5},
	{model="Sanchez",chance=25},
	{model="Sanchez2",chance=16},
	{model="Sanctus",chance=1},
	{model="Sandking",chance=15},
	{model="Sandking2",chance=6},
	{model="Savage",chance=5},
	{model="Schafter2",chance=20},
	{model="Schafter3",chance=5},
	{model="Schafter4",chance=5},
	{model="Schafter5",chance=5},
	{model="Schafter6",chance=5},
	{model="Schwarzer",chance=5},
	{model="Scorcher",chance=13},
	{model="Scrap",chance=23},
	{model="Seminole",chance=5},
	{model="Sentinel",chance=20},
	{model="Sentinel2",chance=5},
	{model="Serrano",chance=1},
	{model="Seven70",chance=1},
	{model="Sheava",chance=1},
	{model="Sheriff",chance=1},
	{model="Sheriff2",chance=1},
	{model="Shotaro",chance=1},
	{model="Skylift",chance=1},
	{model="SlamVan",chance=1},
	{model="SlamVan2",chance=1},
	{model="SlamVan3",chance=1},
	{model="Sovereign",chance=1},
	{model="Specter",chance=1},
	{model="Specter2",chance=1},
	{model="Speeder",chance=1},
	{model="Speeder2",chance=1},
	{model="Speedo",chance=1},
	{model="Speedo2",chance=1},
	{model="Squalo",chance=1},
	{model="Stalion",chance=10},
	{model="Stalion2",chance=1},
	{model="Stanier",chance=20},
	{model="Stinger",chance=1},
	{model="StingerGT",chance=1},
	{model="Stockade",chance=13},
	{model="Stockade3",chance=13},
	{model="Stratum",chance=25},
	{model="Stretch",chance=1},
	{model="Stunt",chance=1},
	{model="Sultan",chance=25},
	{model="SultanRS",chance=1},
	{model="Superd",chance=1},
	{model="Supervolito",chance=1},
	{model="Supervolito2",chance=1},
	{model="Surano",chance=1},
	{model="Surfer",chance=1},
	{model="Surfer2",chance=1},
	{model="Surge",chance=1},
	{model="Swift2",chance=1},
	{model="Swift",chance=1},
	{model="T20",chance=1},
	{model="Taco",chance=1},
	{model="Tailgater",chance=1},
	{model="Tampa",chance=1},
	{model="Tampa2",chance=15},
	{model="Taxi",chance=50},
	{model="Tempesta",chance=1},
	{model="Thrust",chance=1},
	{model="TipTruck",chance=15},
	{model="TipTruck2",chance=15},
	{model="Torero",chance=1},
	{model="Tornado",chance=1},
	{model="Tornado2",chance=1},
	{model="Tornado3",chance=30},
	{model="Tornado4",chance=20},
	{model="Toro",chance=1},
	{model="Toro2",chance=1},
	{model="Tourbus",chance=1},
	{model="TowTruck",chance=5},
	{model="TowTruck2",chance=15},
	{model="Tractor",chance=1},
	{model="Tractor2",chance=1},
	{model="Tractor3",chance=1},
	{model="Trash",chance=15},
	{model="Trash2",chance=15},
	{model="TRFlat",chance=1},
	{model="TriBike",chance=1},
	{model="TriBike2",chance=1},
	{model="TriBike3",chance=1},
	{model="TrophyTruck",chance=15},
	{model="TrophyTruck2",chance=15},
	{model="Tropic",chance=1},
	{model="Tropic2",chance=1},
	{model="Tropos",chance=15},
	{model="Tug",chance=1},
	{model="Turismor",chance=1},
	{model="Turismo2",chance=1},
	{model="Tyrus",chance=1},
	{model="Vacca",chance=1},
	{model="Vader",chance=1},
	{model="Vagner",chance=1},
	{model="Valkyrie",chance=1},
	{model="Valkyrie2",chance=13},
	{model="Velum",chance=1},
	{model="Velum2",chance=1},
	{model="Verlierer2",chance=1},
	{model="Vestra",chance=1},
	{model="Vigero",chance=1},
	{model="Vindicator",chance=1},
	{model="Virgo",chance=18},
	{model="Virgo2",chance=1},
	{model="Virgo3",chance=1},
	{model="Volatus",chance=1},
	{model="Voltic",chance=1},
	{model="Voltic2",chance=1},
	{model="Voodoo",chance=25},
	{model="Voodoo2",chance=1},
	{model="Vortex",chance=1},
	{model="Warrener",chance=1},
	{model="Washington",chance=1},
	{model="Wastelander",chance=30},
	{model="Windsor",chance=1},
	{model="Windsor2",chance=1},
	{model="Wolfsbane",chance=1},
	{model="XA21",chance=1},
	{model="XLS",chance=1},
	{model="XLS2",chance=1},
	{model="Youga",chance=1},
	{model="Youga2",chance=1},
	{model="Zentorno",chance=1},
	{model="Zion",chance=1},
	{model="Zion2",chance=1},
	{model="ZombieA",chance=1},
	{model="ZombieB",chance=1},
	{model="ZType",chance=1}
}


carChances = {}
for i,car in ipairs(spawnableCars) do
	for index = 1, car.chance do
		table.insert(carChances, i)
	end
end


weaponComponents = {
	{
		name="Extended Magazine",
		hash="COMPONENT_PISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_COMBATPISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_APPISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_PISTOL50_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_SNSPISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_HEAVYPISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_HEAVYPISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_VINTAGEPISTOL_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_SMG_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_MICROSMG_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_ASSAULTSMG_CLIP_02",
		price = 2500,
	},

	{
		name="Extended Magazine",
		hash="COMPONENT_GUSENBERG_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_COMBATPDW_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_MG_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_COMBATMG_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_ASSAULTRIFLE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_CARBINERIFLE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_ADVANCEDRIFLE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_SPECIALCARBINE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_BULLPUPRIFLE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_COMPACTRIFLE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_ASSAULTSHOTGUN_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_HEAVYSHOTGUN_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_MARKSMANRIFLE_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_PISTOL_MK2_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_SMG_MK2_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_ASSAULTRIFLE_MK2_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_CARBINERIFLE_MK2_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_COMBATMG_MK2_CLIP_02",
		price = 2500,
	},
	{
		name="Extended Magazine",
		hash="COMPONENT_HEAVYSNIPER_MK2_CLIP_02",
		price = 2500,
	},

	{
		name="Extended Magazine",
		hash="COMPONENT_MARKSMANRIFLE_MK2_CLIP_02",
		price = 2500,
	},
















	{
		name="Very Extended Magazine",
		hash="COMPONENT_COMBATPDW_CLIP_03",
		price = 5000,
	},

	{
		name="Very Extended Magazine",
		hash="COMPONENT_SMG_CLIP_03",
		price = 5000,
	},

	{
		name="Very Extended Magazine",
		hash="COMPONENT_ASSAULTRIFLE_CLIP_03",
		price = 5000,
	},

	{
		name="Very Extended Magazine",
		hash="COMPONENT_CARBINERIFLE_CLIP_03",
		price = 5000,
	},

	{
		name="Very Extended Magazine",
		hash="COMPONENT_SPECIALCARBINE_CLIP_03",
		price = 5000,
	},

	{
		name="Very Extended Magazine",
		hash="COMPONENT_COMPACTRIFLE_CLIP_03",
		price = 5000,
	},

	{
		name="Very Extended Magazine",
		hash="COMPONENT_HEAVYSHOTGUN_CLIP_03",
		price = 5000,
	},



	{
		name="Suppressor",
		hash="COMPONENT_AT_PI_SUPP",
		price = 4500,
	},
	{
		name="Suppressor",
		hash="COMPONENT_AT_PI_SUPP_02",
		price = 4500,
	},
	{
		name="Suppressor",
		hash="COMPONENT_AT_AR_SUPP",
		price = 4500,
	},
	{
		name="Suppressor",
		hash="COMPONENT_AT_AR_SUPP_02",
		price = 4500,
	},

	{
		name="Suppressor",
		hash="COMPONENT_AT_SR_SUPP",
		price = 4500,
	},

	{
		name="Suppressor",
		hash="COMPONENT_AT_SR_SUPP_03",
		price = 4500,
	},


	{
		name="Flashlight",
		hash="COMPONENT_AT_PI_FLSH",
		price = 4500,
	},
	{
		name="Flashlight",
		hash="COMPONENT_AT_AR_FLSH",
		price = 4500,
	},

	{
		name="Flashlight",
		hash="COMPONENT_AT_PI_FLSH_02",
		price = 2500,
	},




	{
		name="Grip",
		hash="COMPONENT_AT_AR_AFGRIP",
		price = 2750,
	},

	{
		name="Grip",
		hash="COMPONENT_AT_AR_AFGRIP_02",
		price = 2750,
	},




	{
		name="Red Dot Sight",
		hash="COMPONENT_AT_PI_RAIL",
		price = 1000,
	},
	{
		name="Holographic Sight",
		hash="COMPONENT_AT_SIGHTS",
		price = 1250,
	},
	{
		name="Red Dot Sight",
		hash="COMPONENT_AT_SCOPE_MACRO",
		price = 1000,
	},
	{
		name="Red Dot Sight",
		hash="COMPONENT_AT_SCOPE_MACRO_MK2",
		price =1000,
	},
	{
		name="Red Dot Sight",
		hash="COMPONENT_AT_SCOPE_MACRO_02",
		price = 1000,
	},
	{
		name="Red Dot Sight",
		hash="COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2",
		price = 1000,
	},

	{
		name="2x Scope",
		hash="COMPONENT_AT_SCOPE_SMALL",
		price = 1300,
	},
	{
		name="2x Scope",
		hash="COMPONENT_AT_SCOPE_SMALL_MK2",
		price = 1300,
	},
	{
		name="2x Scope",
		hash="COMPONENT_AT_SCOPE_SMALL_SMG_MK2",
		price = 1300,
	},
	{
		name="2x Scope",
		hash="COMPONENT_AT_SCOPE_SMALL_02",
		price = 1300,
	},

	{
		name="3.5x Scope",
		hash="COMPONENT_AT_SCOPE_MEDIUM",
		price = 1500,
	},
	{
		name="3.5x Scope",
		hash="COMPONENT_AT_SCOPE_MEDIUM_MK2",
		price = 1500,
	},
	{
		name="Advanced Sniper Scope",
		hash="COMPONENT_AT_SCOPE_MAX",
		price = false,
	},
	{
		name="Compensator",
		hash="COMPONENT_AT_PI_COMP",
		price = 5000,
	},
}




BuyablePeds = {
	{
      name="Default",
      model="s_m_y_armymech_01",
      price = 0,
  },
	{
      name="Bandit",
      model="s_m_y_xmech_02",
      price = -1,
  },
	{
      name="Hero",
      model="s_m_m_chemsec_01",
      price = -1,
  },
	{
      name="Paramedic",
      model="s_m_m_paramedic_01",
      price = 40000,
  },
	{
			name="Survivor",
			model="u_m_y_tattoo_01",
			price = 40000,
	},
	{
			name="Survivor",
			model="ig_josef",
			price = 40000,
	},
	{
			name="Survivor",
			model="ig_hunter",
			price = 40000,
	},
	{
			name="Survivor",
			model="a_f_m_bevhills_01",
			price = 40000,
	},
	{
			name="Gang Survivor",
			model="g_f_y_ballas_01",
			price = 41000,
	},
	{
			name="Gang Survivor",
			model="g_m_y_ballaorig_01",
			price = 41000,
	},
	{
      name="Marine 1",
      model="s_m_m_marine_01",
      price = 48000,
  },
	{
      name="Marine 2",
      model="s_m_y_marine_02",
      price = 48000,
  },
	{
      name="Marine 3",
      model="s_m_y_marine_03",
      price = 50000,
  },
	{
      name="Marine 4",
      model="csb_ramp_marine",
      price = 50000,
  },
	{
      name="Black Ops 1",
      model="s_m_y_blackops_01",
      price = 52000,
  },
	{
      name="Black Ops 2",
      model="s_m_y_blackops_02",
      price = 52000,
  },
	{
			name="SWAT",
			model="s_m_y_swat_01",
			price = 45000,
	},
	{
			name="Bodyguard",
			model="csb_mweather",
			price = 45000,
	},
}




